export const CartActions = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  TOGGLE_PRODUCT: 'TOGGLE_PRODUCT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_REGISTRATION: 'SET_REGISTRATION',
  SET_PAYMENT: 'SET_PAYMENT',
  RESET_CART: 'RESET_CART',
};
