export const CartActions = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  TOGGLE_PRODUCT: 'TOGGLE_PRODUCT',
  SET_QUANTITY: 'SET_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_REGISTRATION: 'SET_REGISTRATION',
  SET_PAYMENT: 'SET_PAYMENT',
  RESET_CART: 'RESET_CART',
};
